---
# Install Ubuntu packages

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: apt-get update
  apt:
    update_cache: yes

- name: Add keys
  apt_key:
    url: "{{ item.url }}"
    id: "{{ item.id }}"
    state: present
  with_items: "{{ repositories.key }}"

- name: Add PPAs
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ repositories.ppa }}"

- name: Add additional repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ repositories.url }}"

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: Install remote packages
  apt:
    deb: "{{ item }}"
  with_items: "{{ remote_packages }}"

- include_tasks: tarexe.yml
  with_items: "{{ remote_executables }}"
  when: item.url.endswith("tar.gz")

- name: Install remote executable
  get_url:
    url: "{{ item.url }}"
    dest: "~/.local/bin/{{ item.name }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755
  with_items: "{{ remote_executables }}"
  when: not item.url.endswith("tar.gz")

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
