---
# Grab a tarball, download it, uncompress it, pull out an executable and add to path

- set_fact:
    bin_path: ~/.local/bin

- name: Ensure directory exists
  file:
    path: "{{ dir }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    recurse: yes
  loop_control:
    loop_var: dir
  with_items:
    - "{{ bin_path }}"

- name: Grab and unpack tarball
  unarchive:
    src: "{{ item.url }}"
    dest: /tmp
    remote_src: yes
    list_files: yes
  register: archive_contents

- name: Copy tar.gz output to bin
  copy:
    src: "/tmp/{{ archive_contents.files[0] }}{{ item.name }}"
    dest: "{{ bin_path }}/{{ item.name }}"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0755
  when: item.url.endswith("tar.gz")

- name: Copy tgz output to bin
  copy:
    src: "/tmp/{{ item.name }}"
    dest: "{{ bin_path }}/{{ item.name }}"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0755
  when: item.url.endswith("tgz")
