shell_exe: /bin/bash

golang:
  name: go
  vm: goenv
  version: 1.9.4
  pkgs:
    - github.com/motemen/ghq    # for remote repo directory management
    - github.com/jingweno/ccat  # colorized cat
    - github.com/knqyf263/pet   # snippet manager
  install_exe: go
  install_cmd: get

# TODO: This freaks out if ~/.local/bin or ~/.local/lib
#       are on path and already have packages
python:
  name: python
  vm: pyenv
  version: 3.6.3
  pkgs:
    - httpie         # pretty curl/wget
    - buku           # cli bookmark manager
    - pre-commit
    - flake8
    - yapf
    - mackup
    - speedtest-cli  # test internet speed
    - rice           # better R shell
    - ipython        # better python shell
    - jedi           # code completion
    - glances        # system info tui
  install_exe: pip3
  install_cmd: install

ruby:
  name: ruby
  vm: rbenv
  version: 2.5.0
  pkgs:
    - vmail          # vim-based email client
  install_exe: gem
  install_cmd: "install --install-dir $GEM_HOME"

node:
  name: node
  vm: nodenv
  version: 6.11.1
  pkgs:
    - yarn
    - prettier
    - eslint
  install_exe: npm
  install_cmd: "install -g"
