---
# Install openvpn profiles

- set_fact:
    target_dir: "{{ data_dir }}/nordvpn"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    recurse: yes
  with_items:
    - "{{ target_dir }}"

- name: Grab Nordvpn ovpn files
  unarchive:
    src: https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip
    dest: "{{ target_dir }}"
    remote_src: yes
  args:
    creates: "{{ target_dir }}"
