---
# list of applications to install
general:
local_home: "{{ lookup('env','HOME') }}"

repositories:
  ppa:
    - "ppa:phoerious/keepassxc"
    - "ppa:marutter/rrutter"

# ubuntu packages
packages:
  - silversearcher-ag
  - bcmwl-kernel-source   # kubuntu wifi fix
  - ctags
  - direnv
  - curl
  - git
  - httpie        # pretty curl/wget
  - jq            # json processor
  - keepassxc     # password manager
  - miller        # csv processor
  - symlinks
  - tree          # pretty directories
  - vim-gtk
  - xclip
  - zsh
  # R packages
  # - r-base
  # - r-base-dev
  # python packages
  - python-setuptools
  - python3
  - python3-dev
  - build-essential
  - libpq-dev
  - libxml2-dev
  - libxslt1-dev
  - libldap2-dev
  - libsasl2-dev
  - libffi-dev
  - libssl-dev

remote_packages:
  - "https://github.com/knqyf263/pet/releases/download/v0.3.0/pet_0.3.0_linux_amd64.deb"
  - "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb"
  # - "https://download1.rstudio.org/rstudio-xenial-1.1.423-amd64.deb"

remote_executables:
  - "https://github.com/jingweno/ccat/releases/download/v1.1.0/linux-amd64-1.1.0.tar.gz"

python_packages:
  - pre-commit
  - flake8
  - yapf
