- name: Grab go
  unarchive:
    src: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local/
    creates: /usr/local/go
    remote_src: yes

- name: Get packages
  shell: "/usr/local/go/bin/go get -u {{ item }}"
  environment:
    GOPATH: "{{ lookup('env', 'HOME') }}/src/go"
  with_items: "{{ go_packages }}"
