- name: Determine OS
  shell: uname
  register: uname_contents

- name: Install Debian packages
  include: packages.yml
  when: uname_contents.stdout.find('Linux') != -1

- name: Install macOS packages
  include: homebrew.yml
  when: uname_contents.stdout.find('Darwin') != -1

- name: Install python packages
  include: python.yml

- name: Install ruby packages
  include: ruby.yml
