---
# Install packages

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: "Add repository '{{ item.name }}' from PPA"
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ repositories.ppa }}"

- name: "Install package '{{ item }}'"
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: "Install remote package '{{ item }}'"
  apt:
    deb: "{{ item }}"
  with_items: "{{ remote_packages }}"

- name: "Install remote executable '{{ item }}'"
  unarchive:
    src: "{{ item }}"
    dest: /usr/local/bin
    remote_src: yes
  with_items: "{{ remote_executables }}"

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
