---
# Install packages

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: apt-get update
  apt:
    update_cache: yes

- name: Add PPAs
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ repositories.ppa }}"

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: Install remote packages
  apt:
    deb: "{{ item }}"
  with_items: "{{ remote_packages }}"

- name: Install remote tarball to local executable
  unarchive:
    src: "{{ item }}"
    dest: /usr/local/bin
    remote_src: yes
  with_items: "{{ remote_executables }}"

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
